// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC212206.U202318609.Capbase.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace PC212206.U202318609.Capbase.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626201314_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PC212206.U202318609.Capbase.Platform.Paperwork.Domain.Model.Aggregates.Covenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Footnotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("footnotes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_covenants");

                    b.ToTable("covenants");
                });

            modelBuilder.Entity("PC212206.U202318609.Capbase.Platform.Paperwork.Domain.Model.Aggregates.Covenant", b =>
                {
                    b.OwnsOne("PC212206.U202318609.Capbase.Platform.Paperwork.Domain.Model.ValueObjects.CapbaseIdentifier", "DocumentIdentifier", b1 =>
                        {
                            b1.Property<int>("CovenantId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("char(36)")
                                .HasColumnName("document_identifier");

                            b1.HasKey("CovenantId")
                                .HasName("p_k_covenants");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_covenants_document_identifier");

                            b1.ToTable("covenants");

                            b1.WithOwner()
                                .HasForeignKey("CovenantId")
                                .HasConstraintName("f_k_covenants_covenants_id");
                        });

                    b.OwnsOne("PC212206.U202318609.Capbase.Platform.Paperwork.Domain.Model.ValueObjects.PartyId", "ClientId", b1 =>
                        {
                            b1.Property<int>("CovenantId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("char(36)")
                                .HasColumnName("client_id");

                            b1.HasKey("CovenantId")
                                .HasName("p_k_covenants");

                            b1.ToTable("covenants");

                            b1.WithOwner()
                                .HasForeignKey("CovenantId")
                                .HasConstraintName("f_k_covenants_covenants_id");
                        });

                    b.OwnsOne("PC212206.U202318609.Capbase.Platform.Shared.Domain.Model.ValueObjects.LegalityPeriod", "Period", b1 =>
                        {
                            b1.Property<int>("CovenantId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("period_end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("period_start_date");

                            b1.HasKey("CovenantId")
                                .HasName("p_k_covenants");

                            b1.ToTable("covenants");

                            b1.WithOwner()
                                .HasForeignKey("CovenantId")
                                .HasConstraintName("f_k_covenants_covenants_id");
                        });

                    b.OwnsOne("PC212206.U202318609.Capbase.Platform.Shared.Domain.Model.ValueObjects.MonetaryAmount", "TotalValue", b1 =>
                        {
                            b1.Property<int>("CovenantId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("varchar(12)")
                                .HasColumnName("monetary_amount_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("monetary_amount_value");

                            b1.HasKey("CovenantId")
                                .HasName("p_k_covenants");

                            b1.ToTable("covenants");

                            b1.WithOwner()
                                .HasForeignKey("CovenantId")
                                .HasConstraintName("f_k_covenants_covenants_id");
                        });

                    b.Navigation("ClientId")
                        .IsRequired();

                    b.Navigation("DocumentIdentifier")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("TotalValue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
